package com.example.zipcodecity.service;

import java.util.ArrayList;

public class SearchCity {

  private ArrayList<City> cities = new ArrayList<>();

  public SearchCity() {
    addCities();
  }

  public City findCity(int zipcode) {
    City foundCity = null;
    for (City city: cities) {
      if (city.getZipCode() == zipcode) {
        foundCity = city;
      }
    }

    return foundCity;
  }


  public void addCities() {
    cities.add(new City(800, "	Høje Taastrup	"));
    cities.add(new City(900, "	København C	"));
    cities.add(new City(917, "	Københavns Pakkecent	"));
    cities.add(new City(960, "	Udland	"));
    cities.add(new City(999, "	København C	"));
    cities.add(new City(1000, "	København K	"));
    cities.add(new City(1050, "	København K	"));
    cities.add(new City(1051, "	København K	"));
    cities.add(new City(1052, "	København K	"));
    cities.add(new City(1053, "	København K	"));
    cities.add(new City(1054, "	København K	"));
    cities.add(new City(1055, "	København K	"));
    cities.add(new City(1056, "	København K	"));
    cities.add(new City(1057, "	København K	"));
    cities.add(new City(1058, "	København K	"));
    cities.add(new City(1059, "	København K	"));
    cities.add(new City(1060, "	København K	"));
    cities.add(new City(1061, "	København K	"));
    cities.add(new City(1062, "	København K	"));
    cities.add(new City(1063, "	København K	"));
    cities.add(new City(1064, "	København K	"));
    cities.add(new City(1065, "	København K	"));
    cities.add(new City(1066, "	København K	"));
    cities.add(new City(1067, "	København K	"));
    cities.add(new City(1068, "	København K	"));
    cities.add(new City(1069, "	København K	"));
    cities.add(new City(1070, "	København K	"));
    cities.add(new City(1071, "	København K	"));
    cities.add(new City(1072, "	København K	"));
    cities.add(new City(1073, "	København K	"));
    cities.add(new City(1074, "	København K	"));
    cities.add(new City(1092, "	København K	"));
    cities.add(new City(1093, "	København K	"));
    cities.add(new City(1095, "	København K	"));
    cities.add(new City(1098, "	København K	"));
    cities.add(new City(1100, "	København K	"));
    cities.add(new City(1101, "	København K	"));
    cities.add(new City(1102, "	København K	"));
    cities.add(new City(1103, "	København K	"));
    cities.add(new City(1104, "	København K	"));
    cities.add(new City(1105, "	København K	"));
    cities.add(new City(1106, "	København K	"));
    cities.add(new City(1107, "	København K	"));
    cities.add(new City(1110, "	København K	"));
    cities.add(new City(1111, "	København K	"));
    cities.add(new City(1112, "	København K	"));
    cities.add(new City(1113, "	København K	"));
    cities.add(new City(1114, "	København K	"));
    cities.add(new City(1115, "	København K	"));
    cities.add(new City(1116, "	København K	"));
    cities.add(new City(1117, "	København K	"));
    cities.add(new City(1118, "	København K	"));
    cities.add(new City(1119, "	København K	"));
    cities.add(new City(1120, "	København K	"));
    cities.add(new City(1121, "	København K	"));
    cities.add(new City(1122, "	København K	"));
    cities.add(new City(1123, "	København K	"));
    cities.add(new City(1124, "	København K	"));
    cities.add(new City(1125, "	København K	"));
    cities.add(new City(1126, "	København K	"));
    cities.add(new City(1127, "	København K	"));
    cities.add(new City(1128, "	København K	"));
    cities.add(new City(1129, "	København K	"));
    cities.add(new City(1130, "	København K	"));
    cities.add(new City(1131, "	København K	"));
    cities.add(new City(1140, "	København K	"));
    cities.add(new City(1147, "	København K	"));
    cities.add(new City(1148, "	København K	"));
    cities.add(new City(1150, "	København K	"));
    cities.add(new City(1151, "	København K	"));
    cities.add(new City(1152, "	København K	"));
    cities.add(new City(1153, "	København K	"));
    cities.add(new City(1154, "	København K	"));
    cities.add(new City(1155, "	København K	"));
    cities.add(new City(1156, "	København K	"));
    cities.add(new City(1157, "	København K	"));
    cities.add(new City(1158, "	København K	"));
    cities.add(new City(1159, "	København K	"));
    cities.add(new City(1160, "	København K	"));
    cities.add(new City(1161, "	København K	"));
    cities.add(new City(1162, "	København K	"));
    cities.add(new City(1164, "	København K	"));
    cities.add(new City(1165, "	København K	"));
    cities.add(new City(1166, "	København K	"));
    cities.add(new City(1167, "	København K	"));
    cities.add(new City(1168, "	København K	"));
    cities.add(new City(1169, "	København K	"));
    cities.add(new City(1170, "	København K	"));
    cities.add(new City(1171, "	København K	"));
    cities.add(new City(1172, "	København K	"));
    cities.add(new City(1173, "	København K	"));
    cities.add(new City(1174, "	København K	"));
    cities.add(new City(1175, "	København K	"));
    cities.add(new City(1200, "	København K	"));
    cities.add(new City(1201, "	København K	"));
    cities.add(new City(1202, "	København K	"));
    cities.add(new City(1203, "	København K	"));
    cities.add(new City(1204, "	København K	"));
    cities.add(new City(1205, "	København K	"));
    cities.add(new City(1206, "	København K	"));
    cities.add(new City(1207, "	København K	"));
    cities.add(new City(1208, "	København K	"));
    cities.add(new City(1209, "	København K	"));
    cities.add(new City(1210, "	København K	"));
    cities.add(new City(1211, "	København K	"));
    cities.add(new City(1213, "	København K	"));
    cities.add(new City(1214, "	København K	"));
    cities.add(new City(1215, "	København K	"));
    cities.add(new City(1216, "	København K	"));
    cities.add(new City(1217, "	København K	"));
    cities.add(new City(1218, "	København K	"));
    cities.add(new City(1219, "	København K	"));
    cities.add(new City(1220, "	København K	"));
    cities.add(new City(1221, "	København K	"));
    cities.add(new City(1240, "	København K	"));
    cities.add(new City(1250, "	København K	"));
    cities.add(new City(1251, "	København K	"));
    cities.add(new City(1253, "	København K	"));
    cities.add(new City(1254, "	København K	"));
    cities.add(new City(1255, "	København K	"));
    cities.add(new City(1256, "	København K	"));
    cities.add(new City(1257, "	København K	"));
    cities.add(new City(1259, "	København K	"));
    cities.add(new City(1260, "	København K	"));
    cities.add(new City(1261, "	København K	"));
    cities.add(new City(1263, "	København K	"));
    cities.add(new City(1264, "	København K	"));
    cities.add(new City(1265, "	København K	"));
    cities.add(new City(1266, "	København K	"));
    cities.add(new City(1267, "	København K	"));
    cities.add(new City(1268, "	København K	"));
    cities.add(new City(1270, "	København K	"));
    cities.add(new City(1271, "	København K	"));
    cities.add(new City(1291, "	København K	"));
    cities.add(new City(1300, "	København K	"));
    cities.add(new City(1301, "	København K	"));
    cities.add(new City(1302, "	København K	"));
    cities.add(new City(1303, "	København K	"));
    cities.add(new City(1304, "	København K	"));
    cities.add(new City(1306, "	København K	"));
    cities.add(new City(1307, "	København K	"));
    cities.add(new City(1308, "	København K	"));
    cities.add(new City(1309, "	København K	"));
    cities.add(new City(1310, "	København K	"));
    cities.add(new City(1311, "	København K	"));
    cities.add(new City(1312, "	København K	"));
    cities.add(new City(1313, "	København K	"));
    cities.add(new City(1314, "	København K	"));
    cities.add(new City(1315, "	København K	"));
    cities.add(new City(1316, "	København K	"));
    cities.add(new City(1317, "	København K	"));
    cities.add(new City(1318, "	København K	"));
    cities.add(new City(1319, "	København K	"));
    cities.add(new City(1320, "	København K	"));
    cities.add(new City(1321, "	København K	"));
    cities.add(new City(1322, "	København K	"));
    cities.add(new City(1323, "	København K	"));
    cities.add(new City(1324, "	København K	"));
    cities.add(new City(1325, "	København K	"));
    cities.add(new City(1326, "	København K	"));
    cities.add(new City(1327, "	København K	"));
    cities.add(new City(1328, "	København K	"));
    cities.add(new City(1329, "	København K	"));
    cities.add(new City(1350, "	København K	"));
    cities.add(new City(1352, "	København K	"));
    cities.add(new City(1353, "	København K	"));
    cities.add(new City(1354, "	København K	"));
    cities.add(new City(1355, "	København K	"));
    cities.add(new City(1356, "	København K	"));
    cities.add(new City(1357, "	København K	"));
    cities.add(new City(1358, "	København K	"));
    cities.add(new City(1359, "	København K	"));
    cities.add(new City(1360, "	København K	"));
    cities.add(new City(1361, "	København K	"));
    cities.add(new City(1362, "	København K	"));
    cities.add(new City(1363, "	København K	"));
    cities.add(new City(1364, "	København K	"));
    cities.add(new City(1365, "	København K	"));
    cities.add(new City(1366, "	København K	"));
    cities.add(new City(1367, "	København K	"));
    cities.add(new City(1368, "	København K	"));
    cities.add(new City(1369, "	København K	"));
    cities.add(new City(1370, "	København K	"));
    cities.add(new City(1371, "	København K	"));
    cities.add(new City(1400, "	København K	"));
    cities.add(new City(1401, "	København K	"));
    cities.add(new City(1402, "	København K	"));
    cities.add(new City(1403, "	København K	"));
    cities.add(new City(1406, "	København K	"));
    cities.add(new City(1407, "	København K	"));
    cities.add(new City(1408, "	København K	"));
    cities.add(new City(1409, "	København K	"));
    cities.add(new City(1410, "	København K	"));
    cities.add(new City(1411, "	København K	"));
    cities.add(new City(1412, "	København K	"));
    cities.add(new City(1413, "	København K	"));
    cities.add(new City(1414, "	København K	"));
    cities.add(new City(1415, "	København K	"));
    cities.add(new City(1416, "	København K	"));
    cities.add(new City(1417, "	København K	"));
    cities.add(new City(1418, "	København K	"));
    cities.add(new City(1419, "	København K	"));
    cities.add(new City(1420, "	København K	"));
    cities.add(new City(1421, "	København K	"));
    cities.add(new City(1422, "	København K	"));
    cities.add(new City(1423, "	København K	"));
    cities.add(new City(1424, "	København K	"));
    cities.add(new City(1425, "	København K	"));
    cities.add(new City(1426, "	København K	"));
    cities.add(new City(1427, "	København K	"));
    cities.add(new City(1428, "	København K	"));
    cities.add(new City(1429, "	København K	"));
    cities.add(new City(1430, "	København K	"));
    cities.add(new City(1431, "	København K	"));
    cities.add(new City(1432, "	København K	"));
    cities.add(new City(1433, "	København K	"));
    cities.add(new City(1434, "	København K	"));
    cities.add(new City(1435, "	København K	"));
    cities.add(new City(1436, "	København K	"));
    cities.add(new City(1437, "	København K	"));
    cities.add(new City(1438, "	København K	"));
    cities.add(new City(1439, "	København K	"));
    cities.add(new City(1440, "	København K	"));
    cities.add(new City(1441, "	København K	"));
    cities.add(new City(1448, "	København K	"));
    cities.add(new City(1450, "	København K	"));
    cities.add(new City(1451, "	København K	"));
    cities.add(new City(1452, "	København K	"));
    cities.add(new City(1453, "	København K	"));
    cities.add(new City(1454, "	København K	"));
    cities.add(new City(1455, "	København K	"));
    cities.add(new City(1456, "	København K	"));
    cities.add(new City(1457, "	København K	"));
    cities.add(new City(1458, "	København K	"));
    cities.add(new City(1459, "	København K	"));
    cities.add(new City(1460, "	København K	"));
    cities.add(new City(1462, "	København K	"));
    cities.add(new City(1463, "	København K	"));
    cities.add(new City(1464, "	København K	"));
    cities.add(new City(1466, "	København K	"));
    cities.add(new City(1467, "	København K	"));
    cities.add(new City(1468, "	København K	"));
    cities.add(new City(1470, "	København K	"));
    cities.add(new City(1471, "	København K	"));
    cities.add(new City(1472, "	København K	"));
    cities.add(new City(1500, "	København V	"));
    cities.add(new City(1513, "	Centraltastning	"));
    cities.add(new City(1532, "	København V	"));
    cities.add(new City(1533, "	København V	"));
    cities.add(new City(1550, "	København V	"));
    cities.add(new City(1551, "	København V	"));
    cities.add(new City(1552, "	København V	"));
    cities.add(new City(1553, "	København V	"));
    cities.add(new City(1554, "	København V	"));
    cities.add(new City(1555, "	København V	"));
    cities.add(new City(1556, "	København V	"));
    cities.add(new City(1557, "	København V	"));
    cities.add(new City(1558, "	København V	"));
    cities.add(new City(1559, "	København V	"));
    cities.add(new City(1560, "	København V	"));
    cities.add(new City(1561, "	København V	"));
    cities.add(new City(1562, "	København V	"));
    cities.add(new City(1563, "	København V	"));
    cities.add(new City(1564, "	København V	"));
    cities.add(new City(1566, "	København V	"));
    cities.add(new City(1567, "	København V	"));
    cities.add(new City(1568, "	København V	"));
    cities.add(new City(1569, "	København V	"));
    cities.add(new City(1570, "	København V	"));
    cities.add(new City(1571, "	København V	"));
    cities.add(new City(1572, "	København V	"));
    cities.add(new City(1573, "	København V	"));
    cities.add(new City(1574, "	København V	"));
    cities.add(new City(1575, "	København V	"));
    cities.add(new City(1576, "	København V	"));
    cities.add(new City(1577, "	København V	"));
    cities.add(new City(1592, "	København V	"));
    cities.add(new City(1599, "	København V	"));
    cities.add(new City(1600, "	København V	"));
    cities.add(new City(1601, "	København V	"));
    cities.add(new City(1602, "	København V	"));
    cities.add(new City(1603, "	København V	"));
    cities.add(new City(1604, "	København V	"));
    cities.add(new City(1606, "	København V	"));
    cities.add(new City(1607, "	København V	"));
    cities.add(new City(1608, "	København V	"));
    cities.add(new City(1609, "	København V	"));
    cities.add(new City(1610, "	København V	"));
    cities.add(new City(1611, "	København V	"));
    cities.add(new City(1612, "	København V	"));
    cities.add(new City(1613, "	København V	"));
    cities.add(new City(1614, "	København V	"));
    cities.add(new City(1615, "	København V	"));
    cities.add(new City(1616, "	København V	"));
    cities.add(new City(1617, "	København V	"));
    cities.add(new City(1618, "	København V	"));
    cities.add(new City(1619, "	København V	"));
    cities.add(new City(1620, "	København V	"));
    cities.add(new City(1621, "	København V	"));
    cities.add(new City(1622, "	København V	"));
    cities.add(new City(1623, "	København V	"));
    cities.add(new City(1624, "	København V	"));
    cities.add(new City(1630, "	København V	"));
    cities.add(new City(1631, "	København V	"));
    cities.add(new City(1632, "	København V	"));
    cities.add(new City(1633, "	København V	"));
    cities.add(new City(1634, "	København V	"));
    cities.add(new City(1635, "	København V	"));
    cities.add(new City(1650, "	København V	"));
    cities.add(new City(1651, "	København V	"));
    cities.add(new City(1652, "	København V	"));
    cities.add(new City(1653, "	København V	"));
    cities.add(new City(1654, "	København V	"));
    cities.add(new City(1655, "	København V	"));
    cities.add(new City(1656, "	København V	"));
    cities.add(new City(1657, "	København V	"));
    cities.add(new City(1658, "	København V	"));
    cities.add(new City(1659, "	København V	"));
    cities.add(new City(1660, "	København V	"));
    cities.add(new City(1661, "	København V	"));
    cities.add(new City(1662, "	København V	"));
    cities.add(new City(1663, "	København V	"));
    cities.add(new City(1664, "	København V	"));
    cities.add(new City(1665, "	København V	"));
    cities.add(new City(1666, "	København V	"));
    cities.add(new City(1667, "	København V	"));
    cities.add(new City(1668, "	København V	"));
    cities.add(new City(1669, "	København V	"));
    cities.add(new City(1670, "	København V	"));
    cities.add(new City(1671, "	København V	"));
    cities.add(new City(1672, "	København V	"));
    cities.add(new City(1673, "	København V	"));
    cities.add(new City(1674, "	København V	"));
    cities.add(new City(1675, "	København V	"));
    cities.add(new City(1676, "	København V	"));
    cities.add(new City(1677, "	København V	"));
    cities.add(new City(1699, "	København V	"));
    cities.add(new City(1700, "	København V	"));
    cities.add(new City(1701, "	København V	"));
    cities.add(new City(1702, "	København V	"));
    cities.add(new City(1703, "	København V	"));
    cities.add(new City(1704, "	København V	"));
    cities.add(new City(1705, "	København V	"));
    cities.add(new City(1706, "	København V	"));
    cities.add(new City(1707, "	København V	"));
    cities.add(new City(1708, "	København V	"));
    cities.add(new City(1709, "	København V	"));
    cities.add(new City(1710, "	København V	"));
    cities.add(new City(1711, "	København V	"));
    cities.add(new City(1712, "	København V	"));
    cities.add(new City(1714, "	København V	"));
    cities.add(new City(1715, "	København V	"));
    cities.add(new City(1716, "	København V	"));
    cities.add(new City(1717, "	København V	"));
    cities.add(new City(1718, "	København V	"));
    cities.add(new City(1719, "	København V	"));
    cities.add(new City(1720, "	København V	"));
    cities.add(new City(1721, "	København V	"));
    cities.add(new City(1722, "	København V	"));
    cities.add(new City(1723, "	København V	"));
    cities.add(new City(1724, "	København V	"));
    cities.add(new City(1725, "	København V	"));
    cities.add(new City(1726, "	København V	"));
    cities.add(new City(1727, "	København V	"));
    cities.add(new City(1728, "	København V	"));
    cities.add(new City(1729, "	København V	"));
    cities.add(new City(1730, "	København V	"));
    cities.add(new City(1731, "	København V	"));
    cities.add(new City(1732, "	København V	"));
    cities.add(new City(1733, "	København V	"));
    cities.add(new City(1734, "	København V	"));
    cities.add(new City(1735, "	København V	"));
    cities.add(new City(1736, "	København V	"));
    cities.add(new City(1737, "	København V	"));
    cities.add(new City(1738, "	København V	"));
    cities.add(new City(1739, "	København V	"));
    cities.add(new City(1749, "	København V	"));
    cities.add(new City(1750, "	København V	"));
    cities.add(new City(1751, "	København V	"));
    cities.add(new City(1752, "	København V	"));
    cities.add(new City(1753, "	København V	"));
    cities.add(new City(1754, "	København V	"));
    cities.add(new City(1755, "	København V	"));
    cities.add(new City(1756, "	København V	"));
    cities.add(new City(1757, "	København V	"));
    cities.add(new City(1758, "	København V	"));
    cities.add(new City(1759, "	København V	"));
    cities.add(new City(1760, "	København V	"));
    cities.add(new City(1761, "	København V	"));
    cities.add(new City(1762, "	København V	"));
    cities.add(new City(1763, "	København V	"));
    cities.add(new City(1764, "	København V	"));
    cities.add(new City(1765, "	København V	"));
    cities.add(new City(1766, "	København V	"));
    cities.add(new City(1770, "	København V	"));
    cities.add(new City(1771, "	København V	"));
    cities.add(new City(1772, "	København V	"));
    cities.add(new City(1773, "	København V	"));
    cities.add(new City(1774, "	København V	"));
    cities.add(new City(1775, "	København V	"));
    cities.add(new City(1777, "	København V	"));
    cities.add(new City(1780, "	København V	"));
    cities.add(new City(1785, "	København V	"));
    cities.add(new City(1786, "	København V	"));
    cities.add(new City(1787, "	København V	"));
    cities.add(new City(1790, "	København V	"));
    cities.add(new City(1799, "	København V	"));
    cities.add(new City(1800, "	Frederiksberg C	"));
    cities.add(new City(1801, "	Frederiksberg C	"));
    cities.add(new City(1802, "	Frederiksberg C	"));
    cities.add(new City(1803, "	Frederiksberg C	"));
    cities.add(new City(1804, "	Frederiksberg C	"));
    cities.add(new City(1805, "	Frederiksberg C	"));
    cities.add(new City(1806, "	Frederiksberg C	"));
    cities.add(new City(1807, "	Frederiksberg C	"));
    cities.add(new City(1808, "	Frederiksberg C	"));
    cities.add(new City(1809, "	Frederiksberg C	"));
    cities.add(new City(1810, "	Frederiksberg C	"));
    cities.add(new City(1811, "	Frederiksberg C	"));
    cities.add(new City(1812, "	Frederiksberg C	"));
    cities.add(new City(1813, "	Frederiksberg C	"));
    cities.add(new City(1814, "	Frederiksberg C	"));
    cities.add(new City(1815, "	Frederiksberg C	"));
    cities.add(new City(1816, "	Frederiksberg C	"));
    cities.add(new City(1817, "	Frederiksberg C	"));
    cities.add(new City(1818, "	Frederiksberg C	"));
    cities.add(new City(1819, "	Frederiksberg C	"));
    cities.add(new City(1820, "	Frederiksberg C	"));
    cities.add(new City(1822, "	Frederiksberg C	"));
    cities.add(new City(1823, "	Frederiksberg C	"));
    cities.add(new City(1824, "	Frederiksberg C	"));
    cities.add(new City(1825, "	Frederiksberg C	"));
    cities.add(new City(1826, "	Frederiksberg C	"));
    cities.add(new City(1827, "	Frederiksberg C	"));
    cities.add(new City(1828, "	Frederiksberg C	"));
    cities.add(new City(1829, "	Frederiksberg C	"));
    cities.add(new City(1850, "	Frederiksberg C	"));
    cities.add(new City(1851, "	Frederiksberg C	"));
    cities.add(new City(1852, "	Frederiksberg C	"));
    cities.add(new City(1853, "	Frederiksberg C	"));
    cities.add(new City(1854, "	Frederiksberg C	"));
    cities.add(new City(1855, "	Frederiksberg C	"));
    cities.add(new City(1856, "	Frederiksberg C	"));
    cities.add(new City(1857, "	Frederiksberg C	"));
    cities.add(new City(1860, "	Frederiksberg C	"));
    cities.add(new City(1861, "	Frederiksberg C	"));
    cities.add(new City(1862, "	Frederiksberg C	"));
    cities.add(new City(1863, "	Frederiksberg C	"));
    cities.add(new City(1864, "	Frederiksberg C	"));
    cities.add(new City(1865, "	Frederiksberg C	"));
    cities.add(new City(1866, "	Frederiksberg C	"));
    cities.add(new City(1867, "	Frederiksberg C	"));
    cities.add(new City(1868, "	Frederiksberg C	"));
    cities.add(new City(1870, "	Frederiksberg C	"));
    cities.add(new City(1871, "	Frederiksberg C	"));
    cities.add(new City(1872, "	Frederiksberg C	"));
    cities.add(new City(1873, "	Frederiksberg C	"));
    cities.add(new City(1874, "	Frederiksberg C	"));
    cities.add(new City(1875, "	Frederiksberg C	"));
    cities.add(new City(1876, "	Frederiksberg C	"));
    cities.add(new City(1877, "	Frederiksberg C	"));
    cities.add(new City(1878, "	Frederiksberg C	"));
    cities.add(new City(1879, "	Frederiksberg C	"));
    cities.add(new City(1900, "	Frederiksberg C	"));
    cities.add(new City(1901, "	Frederiksberg C	"));
    cities.add(new City(1902, "	Frederiksberg C	"));
    cities.add(new City(1903, "	Frederiksberg C	"));
    cities.add(new City(1904, "	Frederiksberg C	"));
    cities.add(new City(1905, "	Frederiksberg C	"));
    cities.add(new City(1906, "	Frederiksberg C	"));
    cities.add(new City(1908, "	Frederiksberg C	"));
    cities.add(new City(1909, "	Frederiksberg C	"));
    cities.add(new City(1910, "	Frederiksberg C	"));
    cities.add(new City(1911, "	Frederiksberg C	"));
    cities.add(new City(1912, "	Frederiksberg C	"));
    cities.add(new City(1913, "	Frederiksberg C	"));
    cities.add(new City(1914, "	Frederiksberg C	"));
    cities.add(new City(1915, "	Frederiksberg C	"));
    cities.add(new City(1916, "	Frederiksberg C	"));
    cities.add(new City(1917, "	Frederiksberg C	"));
    cities.add(new City(1920, "	Frederiksberg C	"));
    cities.add(new City(1921, "	Frederiksberg C	"));
    cities.add(new City(1922, "	Frederiksberg C	"));
    cities.add(new City(1923, "	Frederiksberg C	"));
    cities.add(new City(1924, "	Frederiksberg C	"));
    cities.add(new City(1925, "	Frederiksberg C	"));
    cities.add(new City(1926, "	Frederiksberg C	"));
    cities.add(new City(1927, "	Frederiksberg C	"));
    cities.add(new City(1928, "	Frederiksberg C	"));
    cities.add(new City(1950, "	Frederiksberg C	"));
    cities.add(new City(1951, "	Frederiksberg C	"));
    cities.add(new City(1952, "	Frederiksberg C	"));
    cities.add(new City(1953, "	Frederiksberg C	"));
    cities.add(new City(1954, "	Frederiksberg C	"));
    cities.add(new City(1955, "	Frederiksberg C	"));
    cities.add(new City(1956, "	Frederiksberg C	"));
    cities.add(new City(1957, "	Frederiksberg C	"));
    cities.add(new City(1958, "	Frederiksberg C	"));
    cities.add(new City(1959, "	Frederiksberg C	"));
    cities.add(new City(1960, "	Frederiksberg C	"));
    cities.add(new City(1961, "	Frederiksberg C	"));
    cities.add(new City(1962, "	Frederiksberg C	"));
    cities.add(new City(1963, "	Frederiksberg C	"));
    cities.add(new City(1964, "	Frederiksberg C	"));
    cities.add(new City(1965, "	Frederiksberg C	"));
    cities.add(new City(1966, "	Frederiksberg C	"));
    cities.add(new City(1967, "	Frederiksberg C	"));
    cities.add(new City(1970, "	Frederiksberg C	"));
    cities.add(new City(1971, "	Frederiksberg C	"));
    cities.add(new City(1972, "	Frederiksberg C	"));
    cities.add(new City(1973, "	Frederiksberg C	"));
    cities.add(new City(1974, "	Frederiksberg C	"));
    cities.add(new City(2000, "	Frederiksberg	"));
    cities.add(new City(2100, "	København Ø	"));
    cities.add(new City(2150, "	Nordhavn	"));
    cities.add(new City(2200, "	København N	"));
    cities.add(new City(2300, "	København S	"));
    cities.add(new City(2400, "	København NV	"));
    cities.add(new City(2450, "	København SV	"));
    cities.add(new City(2500, "	Valby	"));
    cities.add(new City(2600, "	Glostrup	"));
    cities.add(new City(2605, "	Brøndby	"));
    cities.add(new City(2610, "	Rødovre	"));
    cities.add(new City(2620, "	Albertslund	"));
    cities.add(new City(2625, "	Vallensbæk	"));
    cities.add(new City(2630, "	Taastrup	"));
    cities.add(new City(2635, "	Ishøj	"));
    cities.add(new City(2640, "	Hedehusene	"));
    cities.add(new City(2650, "	Hvidovre	"));
    cities.add(new City(2660, "	Brøndby Strand	"));
    cities.add(new City(2665, "	Vallensbæk Strand	"));
    cities.add(new City(2670, "	Greve	"));
    cities.add(new City(2680, "	Solrød Strand	"));
    cities.add(new City(2690, "	Karlslunde	"));
    cities.add(new City(2700, "	Brønshøj	"));
    cities.add(new City(2720, "	Vanløse	"));
    cities.add(new City(2730, "	Herlev	"));
    cities.add(new City(2740, "	Skovlunde	"));
    cities.add(new City(2750, "	Ballerup	"));
    cities.add(new City(2760, "	Måløv	"));
    cities.add(new City(2765, "	Smørum	"));
    cities.add(new City(2770, "	Kastrup	"));
    cities.add(new City(2791, "	Dragør	"));
    cities.add(new City(2800, "	Kongens Lyngby	"));
    cities.add(new City(2820, "	Gentofte	"));
    cities.add(new City(2830, "	Virum	"));
    cities.add(new City(2840, "	Holte	"));
    cities.add(new City(2850, "	Nærum	"));
    cities.add(new City(2860, "	Søborg	"));
    cities.add(new City(2870, "	Dyssegård	"));
    cities.add(new City(2880, "	Bagsværd	"));
    cities.add(new City(2900, "	Hellerup	"));
    cities.add(new City(2920, "	Charlottenlund	"));
    cities.add(new City(2930, "	Klampenborg	"));
    cities.add(new City(2942, "	Skodsborg	"));
    cities.add(new City(2950, "	Vedbæk	"));
    cities.add(new City(2960, "	Rungsted Kyst	"));
    cities.add(new City(2970, "	Hørsholm	"));
    cities.add(new City(2980, "	Kokkedal	"));
    cities.add(new City(2990, "	Nivå	"));
    cities.add(new City(3000, "	Helsingør	"));
    cities.add(new City(3050, "	Humlebæk	"));
    cities.add(new City(3060, "	Espergærde	"));
    cities.add(new City(3070, "	Snekkersten	"));
    cities.add(new City(3080, "	Tikøb	"));
    cities.add(new City(3100, "	Hornbæk	"));
    cities.add(new City(3120, "	Dronningmølle	"));
    cities.add(new City(3140, "	Ålsgårde	"));
    cities.add(new City(3150, "	Hellebæk	"));
    cities.add(new City(3200, "	Helsinge	"));
    cities.add(new City(3210, "	Vejby	"));
    cities.add(new City(3220, "	Tisvildeleje	"));
    cities.add(new City(3230, "	Græsted	"));
    cities.add(new City(3250, "	Gilleleje	"));
    cities.add(new City(3300, "	Frederiksværk	"));
    cities.add(new City(3310, "	Ølsted	"));
    cities.add(new City(3320, "	Skævinge	"));
    cities.add(new City(3330, "	Gørløse	"));
    cities.add(new City(3360, "	Liseleje	"));
    cities.add(new City(3370, "	Melby	"));
    cities.add(new City(3390, "	Hundested	"));
    cities.add(new City(3400, "	Hillerød	"));
    cities.add(new City(3450, "	Allerød	"));
    cities.add(new City(3460, "	Birkerød	"));
    cities.add(new City(3480, "	Fredensborg	"));
    cities.add(new City(3490, "	Kvistgård	"));
    cities.add(new City(3500, "	Værløse	"));
    cities.add(new City(3520, "	Farum	"));
    cities.add(new City(3540, "	Lynge	"));
    cities.add(new City(3550, "	Slangerup	"));
    cities.add(new City(3600, "	Frederikssund	"));
    cities.add(new City(3630, "	Jægerspris	"));
    cities.add(new City(3650, "	Ølstykke	"));
    cities.add(new City(3660, "	Stenløse	"));
    cities.add(new City(3670, "	Veksø Sjælland	"));
    cities.add(new City(3700, "	Rønne	"));
    cities.add(new City(3720, "	Aakirkeby	"));
    cities.add(new City(3730, "	Nexø	"));
    cities.add(new City(3740, "	Svaneke	"));
    cities.add(new City(3751, "	Østermarie	"));
    cities.add(new City(3760, "	Gudhjem	"));
    cities.add(new City(3770, "	Allinge	"));
    cities.add(new City(3782, "	Klemensker	"));
    cities.add(new City(3790, "	Hasle	"));
    cities.add(new City(4000, "	Roskilde	"));
    cities.add(new City(4030, "	Tune	"));
    cities.add(new City(4040, "	Jyllinge	"));
    cities.add(new City(4050, "	Skibby	"));
    cities.add(new City(4060, "	Kirke Såby	"));
    cities.add(new City(4070, "	Kirke Hyllinge	"));
    cities.add(new City(4100, "	Ringsted	"));
    cities.add(new City(4130, "	Viby Sjælland	"));
    cities.add(new City(4140, "	Borup	"));
    cities.add(new City(4160, "	Herlufmagle	"));
    cities.add(new City(4171, "	Glumsø	"));
    cities.add(new City(4173, "	Fjenneslev	"));
    cities.add(new City(4174, "	Jystrup Midtsj	"));
    cities.add(new City(4180, "	Sorø	"));
    cities.add(new City(4190, "	Munke Bjergby	"));
    cities.add(new City(4200, "	Slagelse	"));
    cities.add(new City(4220, "	Korsør	"));
    cities.add(new City(4230, "	Skælskør	"));
    cities.add(new City(4241, "	Vemmelev	"));
    cities.add(new City(4242, "	Boeslunde	"));
    cities.add(new City(4243, "	Rude	"));
    cities.add(new City(4250, "	Fuglebjerg	"));
    cities.add(new City(4261, "	Dalmose	"));
    cities.add(new City(4262, "	Sandved	"));
    cities.add(new City(4270, "	Høng	"));
    cities.add(new City(4281, "	Gørlev	"));
    cities.add(new City(4291, "	Ruds Vedby	"));
    cities.add(new City(4293, "	Dianalund	"));
    cities.add(new City(4295, "	Stenlille	"));
    cities.add(new City(4296, "	Nyrup	"));
    cities.add(new City(4300, "	Holbæk	"));
    cities.add(new City(4320, "	Lejre	"));
    cities.add(new City(4330, "	Hvalsø	"));
    cities.add(new City(4340, "	Tølløse	"));
    cities.add(new City(4350, "	Ugerløse	"));
    cities.add(new City(4360, "	Kirke Eskilstrup	"));
    cities.add(new City(4370, "	Store Merløse	"));
    cities.add(new City(4390, "	Vipperød	"));
    cities.add(new City(4400, "	Kalundborg	"));
    cities.add(new City(4420, "	Regstrup	"));
    cities.add(new City(4440, "	Mørkøv	"));
    cities.add(new City(4450, "	Jyderup	"));
    cities.add(new City(4460, "	Snertinge	"));
    cities.add(new City(4470, "	Svebølle	"));
    cities.add(new City(4480, "	Store Fuglede	"));
    cities.add(new City(4490, "	Jerslev Sjælland	"));
    cities.add(new City(4500, "	Nykøbing Sj	"));
    cities.add(new City(4520, "	Svinninge	"));
    cities.add(new City(4532, "	Gislinge	"));
    cities.add(new City(4534, "	Hørve	"));
    cities.add(new City(4540, "	Fårevejle	"));
    cities.add(new City(4550, "	Asnæs	"));
    cities.add(new City(4560, "	Vig	"));
    cities.add(new City(4571, "	Grevinge	"));
    cities.add(new City(4572, "	Nørre Asmindrup	"));
    cities.add(new City(4573, "	Højby	"));
    cities.add(new City(4581, "	Rørvig	"));
    cities.add(new City(4583, "	Sjællands Odde	"));
    cities.add(new City(4591, "	Føllenslev	"));
    cities.add(new City(4592, "	Sejerø	"));
    cities.add(new City(4593, "	Eskebjerg	"));
    cities.add(new City(4600, "	Køge	"));
    cities.add(new City(4621, "	Gadstrup	"));
    cities.add(new City(4622, "	Havdrup	"));
    cities.add(new City(4623, "	Lille Skensved	"));
    cities.add(new City(4632, "	Bjæverskov	"));
    cities.add(new City(4640, "	Faxe	"));
    cities.add(new City(4652, "	Hårlev	"));
    cities.add(new City(4653, "	Karise	"));
    cities.add(new City(4654, "	Faxe Ladeplads	"));
    cities.add(new City(4660, "	Store Heddinge	"));
    cities.add(new City(4671, "	Strøby	"));
    cities.add(new City(4672, "	Klippinge	"));
    cities.add(new City(4673, "	Rødvig Stevns	"));
    cities.add(new City(4681, "	Herfølge	"));
    cities.add(new City(4682, "	Tureby	"));
    cities.add(new City(4683, "	Rønnede	"));
    cities.add(new City(4684, "	Holmegaard	"));
    cities.add(new City(4690, "	Haslev	"));
    cities.add(new City(4700, "	Næstved	"));
    cities.add(new City(4720, "	Præstø	"));
    cities.add(new City(4733, "	Tappernøje	"));
    cities.add(new City(4735, "	Mern	"));
    cities.add(new City(4736, "	Karrebæksminde	"));
    cities.add(new City(4750, "	Lundby	"));
    cities.add(new City(4760, "	Vordingborg	"));
    cities.add(new City(4771, "	Kalvehave	"));
    cities.add(new City(4772, "	Langebæk	"));
    cities.add(new City(4773, "	Stensved	"));
    cities.add(new City(4780, "	Stege	"));
    cities.add(new City(4791, "	Borre	"));
    cities.add(new City(4792, "	Askeby	"));
    cities.add(new City(4793, "	Bogø By	"));
    cities.add(new City(4800, "	Nykøbing F	"));
    cities.add(new City(4840, "	Nørre Alslev	"));
    cities.add(new City(4850, "	Stubbekøbing	"));
    cities.add(new City(4862, "	Guldborg	"));
    cities.add(new City(4863, "	Eskilstrup	"));
    cities.add(new City(4871, "	Horbelev	"));
    cities.add(new City(4872, "	Idestrup	"));
    cities.add(new City(4873, "	Væggerløse	"));
    cities.add(new City(4874, "	Gedser	"));
    cities.add(new City(4880, "	Nysted	"));
    cities.add(new City(4891, "	Toreby L	"));
    cities.add(new City(4892, "	Kettinge	"));
    cities.add(new City(4894, "	Øster Ulslev	"));
    cities.add(new City(4895, "	Errindlev	"));
    cities.add(new City(4900, "	Nakskov	"));
    cities.add(new City(4912, "	Harpelunde	"));
    cities.add(new City(4913, "	Horslunde	"));
    cities.add(new City(4920, "	Søllested	"));
    cities.add(new City(4930, "	Maribo	"));
    cities.add(new City(4941, "	Bandholm	"));
    cities.add(new City(4943, "	Torrig L	"));
    cities.add(new City(4944, "	Fejø	"));
    cities.add(new City(4951, "	Nørreballe	"));
    cities.add(new City(4952, "	Stokkemarke	"));
    cities.add(new City(4953, "	Vesterborg	"));
    cities.add(new City(4960, "	Holeby	"));
    cities.add(new City(4970, "	Rødby	"));
    cities.add(new City(4983, "	Dannemare	"));
    cities.add(new City(4990, "	Sakskøbing	"));
    cities.add(new City(5000, "	Odense C	"));
    cities.add(new City(5200, "	Odense V	"));
    cities.add(new City(5210, "	Odense NV	"));
    cities.add(new City(5220, "	Odense SØ	"));
    cities.add(new City(5230, "	Odense M	"));
    cities.add(new City(5240, "	Odense NØ	"));
    cities.add(new City(5250, "	Odense SV	"));
    cities.add(new City(5260, "	Odense S	"));
    cities.add(new City(5270, "	Odense N	"));
    cities.add(new City(5290, "	Marslev	"));
    cities.add(new City(5300, "	Kerteminde	"));
    cities.add(new City(5320, "	Agedrup	"));
    cities.add(new City(5330, "	Munkebo	"));
    cities.add(new City(5350, "	Rynkeby	"));
    cities.add(new City(5370, "	Mesinge	"));
    cities.add(new City(5380, "	Dalby	"));
    cities.add(new City(5390, "	Martofte	"));
    cities.add(new City(5400, "	Bogense	"));
    cities.add(new City(5450, "	Otterup	"));
    cities.add(new City(5462, "	Morud	"));
    cities.add(new City(5463, "	Harndrup	"));
    cities.add(new City(5464, "	Brenderup Fyn	"));
    cities.add(new City(5466, "	Asperup	"));
    cities.add(new City(5471, "	Søndersø	"));
    cities.add(new City(5474, "	Veflinge	"));
    cities.add(new City(5485, "	Skamby	"));
    cities.add(new City(5491, "	Blommenslyst	"));
    cities.add(new City(5492, "	Vissenbjerg	"));
    cities.add(new City(5500, "	Middelfart	"));
    cities.add(new City(5540, "	Ullerslev	"));
    cities.add(new City(5550, "	Langeskov	"));
    cities.add(new City(5560, "	Aarup	"));
    cities.add(new City(5580, "	Nørre Aaby	"));
    cities.add(new City(5591, "	Gelsted	"));
    cities.add(new City(5592, "	Ejby	"));
    cities.add(new City(5600, "	Faaborg	"));
    cities.add(new City(5610, "	Assens	"));
    cities.add(new City(5620, "	Glamsbjerg	"));
    cities.add(new City(5631, "	Ebberup	"));
    cities.add(new City(5642, "	Millinge	"));
    cities.add(new City(5672, "	Broby	"));
    cities.add(new City(5683, "	Haarby	"));
    cities.add(new City(5690, "	Tommerup	"));
    cities.add(new City(5700, "	Svendborg	"));
    cities.add(new City(5750, "	Ringe	"));
    cities.add(new City(5762, "	Vester Skerninge	"));
    cities.add(new City(5771, "	Stenstrup	"));
    cities.add(new City(5772, "	Kværndrup	"));
    cities.add(new City(5792, "	Årslev	"));
    cities.add(new City(5800, "	Nyborg	"));
    cities.add(new City(5853, "	Ørbæk	"));
    cities.add(new City(5854, "	Gislev	"));
    cities.add(new City(5856, "	Ryslinge	"));
    cities.add(new City(5863, "	Ferritslev Fyn	"));
    cities.add(new City(5871, "	Frørup	"));
    cities.add(new City(5874, "	Hesselager	"));
    cities.add(new City(5881, "	Skårup Fyn	"));
    cities.add(new City(5882, "	Vejstrup	"));
    cities.add(new City(5883, "	Oure	"));
    cities.add(new City(5884, "	Gudme	"));
    cities.add(new City(5892, "	Gudbjerg Sydfyn	"));
    cities.add(new City(5900, "	Rudkøbing	"));
    cities.add(new City(5932, "	Humble	"));
    cities.add(new City(5935, "	Bagenkop	"));
    cities.add(new City(5953, "	Tranekær	"));
    cities.add(new City(5960, "	Marstal	"));
    cities.add(new City(5970, "	Ærøskøbing	"));
    cities.add(new City(5985, "	Søby Ærø	"));
    cities.add(new City(6000, "	Kolding	"));
    cities.add(new City(6040, "	Egtved	"));
    cities.add(new City(6051, "	Almind	"));
    cities.add(new City(6052, "	Viuf	"));
    cities.add(new City(6064, "	Jordrup	"));
    cities.add(new City(6070, "	Christiansfeld	"));
    cities.add(new City(6091, "	Bjert	"));
    cities.add(new City(6092, "	Sønder Stenderup	"));
    cities.add(new City(6093, "	Sjølund	"));
    cities.add(new City(6094, "	Hejls	"));
    cities.add(new City(6100, "	Haderslev	"));
    cities.add(new City(6200, "	Aabenraa	"));
    cities.add(new City(6230, "	Rødekro	"));
    cities.add(new City(6240, "	Løgumkloster	"));
    cities.add(new City(6261, "	Bredebro	"));
    cities.add(new City(6270, "	Tønder	"));
    cities.add(new City(6280, "	Højer	"));
    cities.add(new City(6300, "	Gråsten	"));
    cities.add(new City(6310, "	Broager	"));
    cities.add(new City(6320, "	Egernsund	"));
    cities.add(new City(6330, "	Padborg	"));
    cities.add(new City(6340, "	Kruså	"));
    cities.add(new City(6360, "	Tinglev	"));
    cities.add(new City(6372, "	Bylderup-Bov	"));
    cities.add(new City(6392, "	Bolderslev	"));
    cities.add(new City(6400, "	Sønderborg	"));
    cities.add(new City(6430, "	Nordborg	"));
    cities.add(new City(6440, "	Augustenborg	"));
    cities.add(new City(6470, "	Sydals	"));
    cities.add(new City(6500, "	Vojens	"));
    cities.add(new City(6510, "	Gram	"));
    cities.add(new City(6520, "	Toftlund	"));
    cities.add(new City(6534, "	Agerskov	"));
    cities.add(new City(6535, "	Branderup J	"));
    cities.add(new City(6541, "	Bevtoft	"));
    cities.add(new City(6560, "	Sommersted	"));
    cities.add(new City(6580, "	Vamdrup	"));
    cities.add(new City(6600, "	Vejen	"));
    cities.add(new City(6621, "	Gesten	"));
    cities.add(new City(6622, "	Bække	"));
    cities.add(new City(6623, "	Vorbasse	"));
    cities.add(new City(6630, "	Rødding	"));
    cities.add(new City(6640, "	Lunderskov	"));
    cities.add(new City(6650, "	Brørup	"));
    cities.add(new City(6660, "	Lintrup	"));
    cities.add(new City(6670, "	Holsted	"));
    cities.add(new City(6682, "	Hovborg	"));
    cities.add(new City(6683, "	Føvling	"));
    cities.add(new City(6690, "	Gørding	"));
    cities.add(new City(6700, "	Esbjerg	"));
    cities.add(new City(6705, "	Esbjerg Ø	"));
    cities.add(new City(6710, "	Esbjerg V	"));
    cities.add(new City(6715, "	Esbjerg N	"));
    cities.add(new City(6720, "	Fanø	"));
    cities.add(new City(6731, "	Tjæreborg	"));
    cities.add(new City(6740, "	Bramming	"));
    cities.add(new City(6752, "	Glejbjerg	"));
    cities.add(new City(6753, "	Agerbæk	"));
    cities.add(new City(6760, "	Ribe	"));
    cities.add(new City(6771, "	Gredstedbro	"));
    cities.add(new City(6780, "	Skærbæk	"));
    cities.add(new City(6792, "	Rømø	"));
    cities.add(new City(6800, "	Varde	"));
    cities.add(new City(6818, "	Årre	"));
    cities.add(new City(6823, "	Ansager	"));
    cities.add(new City(6830, "	Nørre Nebel	"));
    cities.add(new City(6840, "	Oksbøl	"));
    cities.add(new City(6851, "	Janderup Vestj	"));
    cities.add(new City(6852, "	Billum	"));
    cities.add(new City(6853, "	Vejers Strand	"));
    cities.add(new City(6854, "	Henne	"));
    cities.add(new City(6855, "	Outrup	"));
    cities.add(new City(6857, "	Blåvand	"));
    cities.add(new City(6862, "	Tistrup	"));
    cities.add(new City(6870, "	Ølgod	"));
    cities.add(new City(6880, "	Tarm	"));
    cities.add(new City(6893, "	Hemmet	"));
    cities.add(new City(6900, "	Skjern	"));
    cities.add(new City(6920, "	Videbæk	"));
    cities.add(new City(6933, "	Kibæk	"));
    cities.add(new City(6940, "	Lem St	"));
    cities.add(new City(6950, "	Ringkøbing	"));
    cities.add(new City(6960, "	Hvide Sande	"));
    cities.add(new City(6971, "	Spjald	"));
    cities.add(new City(6973, "	Ørnhøj	"));
    cities.add(new City(6980, "	Tim	"));
    cities.add(new City(6990, "	Ulfborg	"));
    cities.add(new City(7000, "	Fredericia	"));
    cities.add(new City(7007, "	Fredericia	"));
    cities.add(new City(7080, "	Børkop	"));
    cities.add(new City(7100, "	Vejle	"));
    cities.add(new City(7120, "	Vejle Øst	"));
    cities.add(new City(7130, "	Juelsminde	"));
    cities.add(new City(7140, "	Stouby	"));
    cities.add(new City(7150, "	Barrit	"));
    cities.add(new City(7160, "	Tørring	"));
    cities.add(new City(7171, "	Uldum	"));
    cities.add(new City(7173, "	Vonge	"));
    cities.add(new City(7182, "	Bredsten	"));
    cities.add(new City(7183, "	Randbøl	"));
    cities.add(new City(7184, "	Vandel	"));
    cities.add(new City(7190, "	Billund	"));
    cities.add(new City(7200, "	Grindsted	"));
    cities.add(new City(7250, "	Hejnsvig	"));
    cities.add(new City(7260, "	Sønder Omme	"));
    cities.add(new City(7270, "	Stakroge	"));
    cities.add(new City(7280, "	Sønder Felding	"));
    cities.add(new City(7300, "	Jelling	"));
    cities.add(new City(7321, "	Gadbjerg	"));
    cities.add(new City(7323, "	Give	"));
    cities.add(new City(7330, "	Brande	"));
    cities.add(new City(7361, "	Ejstrupholm	"));
    cities.add(new City(7362, "	Hampen	"));
    cities.add(new City(7400, "	Herning	"));
    cities.add(new City(7430, "	Ikast	"));
    cities.add(new City(7441, "	Bording	"));
    cities.add(new City(7442, "	Engesvang	"));
    cities.add(new City(7451, "	Sunds	"));
    cities.add(new City(7470, "	Karup J	"));
    cities.add(new City(7480, "	Vildbjerg	"));
    cities.add(new City(7490, "	Aulum	"));
    cities.add(new City(7500, "	Holstebro	"));
    cities.add(new City(7540, "	Haderup	"));
    cities.add(new City(7550, "	Sørvad	"));
    cities.add(new City(7560, "	Hjerm	"));
    cities.add(new City(7570, "	Vemb	"));
    cities.add(new City(7600, "	Struer	"));
    cities.add(new City(7620, "	Lemvig	"));
    cities.add(new City(7650, "	Bøvlingbjerg	"));
    cities.add(new City(7660, "	Bækmarksbro	"));
    cities.add(new City(7673, "	Harboøre	"));
    cities.add(new City(7680, "	Thyborøn	"));
    cities.add(new City(7700, "	Thisted	"));
    cities.add(new City(7730, "	Hanstholm	"));
    cities.add(new City(7741, "	Frøstrup	"));
    cities.add(new City(7742, "	Vesløs	"));
    cities.add(new City(7752, "	Snedsted	"));
    cities.add(new City(7755, "	Bedsted Thy	"));
    cities.add(new City(7760, "	Hurup Thy	"));
    cities.add(new City(7770, "	Vestervig	"));
    cities.add(new City(7790, "	Thyholm	"));
    cities.add(new City(7800, "	Skive	"));
    cities.add(new City(7830, "	Vinderup	"));
    cities.add(new City(7840, "	Højslev	"));
    cities.add(new City(7850, "	Stoholm Jyll	"));
    cities.add(new City(7860, "	Spøttrup	"));
    cities.add(new City(7870, "	Roslev	"));
    cities.add(new City(7884, "	Fur	"));
    cities.add(new City(7900, "	Nykøbing M	"));
    cities.add(new City(7950, "	Erslev	"));
    cities.add(new City(7960, "	Karby	"));
    cities.add(new City(7970, "	Redsted M	"));
    cities.add(new City(7980, "	Vils	"));
    cities.add(new City(7990, "	Øster Assels	"));
    cities.add(new City(8000, "	Aarhus C	"));
    cities.add(new City(8200, "	Aarhus N	"));
    cities.add(new City(8210, "	Aarhus V	"));
    cities.add(new City(8220, "	Brabrand	"));
    cities.add(new City(8230, "	Åbyhøj	"));
    cities.add(new City(8240, "	Risskov	"));
    cities.add(new City(8245, "	Risskov Ø	"));
    cities.add(new City(8250, "	Egå	"));
    cities.add(new City(8260, "	Viby J	"));
    cities.add(new City(8270, "	Højbjerg	"));
    cities.add(new City(8300, "	Odder	"));
    cities.add(new City(8305, "	Samsø	"));
    cities.add(new City(8310, "	Tranbjerg J	"));
    cities.add(new City(8320, "	Mårslet	"));
    cities.add(new City(8330, "	Beder	"));
    cities.add(new City(8340, "	Malling	"));
    cities.add(new City(8350, "	Hundslund	"));
    cities.add(new City(8355, "	Solbjerg	"));
    cities.add(new City(8361, "	Hasselager	"));
    cities.add(new City(8362, "	Hørning	"));
    cities.add(new City(8370, "	Hadsten	"));
    cities.add(new City(8380, "	Trige	"));
    cities.add(new City(8381, "	Tilst	"));
    cities.add(new City(8382, "	Hinnerup	"));
    cities.add(new City(8400, "	Ebeltoft	"));
    cities.add(new City(8410, "	Rønde	"));
    cities.add(new City(8420, "	Knebel	"));
    cities.add(new City(8444, "	Balle	"));
    cities.add(new City(8450, "	Hammel	"));
    cities.add(new City(8462, "	Harlev J	"));
    cities.add(new City(8464, "	Galten	"));
    cities.add(new City(8471, "	Sabro	"));
    cities.add(new City(8472, "	Sporup	"));
    cities.add(new City(8500, "	Grenaa	"));
    cities.add(new City(8520, "	Lystrup	"));
    cities.add(new City(8530, "	Hjortshøj	"));
    cities.add(new City(8541, "	Skødstrup	"));
    cities.add(new City(8543, "	Hornslet	"));
    cities.add(new City(8544, "	Mørke	"));
    cities.add(new City(8550, "	Ryomgård	"));
    cities.add(new City(8560, "	Kolind	"));
    cities.add(new City(8570, "	Trustrup	"));
    cities.add(new City(8581, "	Nimtofte	"));
    cities.add(new City(8585, "	Glesborg	"));
    cities.add(new City(8586, "	Ørum Djurs	"));
    cities.add(new City(8592, "	Anholt	"));
    cities.add(new City(8600, "	Silkeborg	"));
    cities.add(new City(8620, "	Kjellerup	"));
    cities.add(new City(8632, "	Lemming	"));
    cities.add(new City(8641, "	Sorring	"));
    cities.add(new City(8643, "	Ans By	"));
    cities.add(new City(8653, "	Them	"));
    cities.add(new City(8654, "	Bryrup	"));
    cities.add(new City(8660, "	Skanderborg	"));
    cities.add(new City(8670, "	Låsby	"));
    cities.add(new City(8680, "	Ry	"));
    cities.add(new City(8700, "	Horsens	"));
    cities.add(new City(8721, "	Daugård	"));
    cities.add(new City(8722, "	Hedensted	"));
    cities.add(new City(8723, "	Løsning	"));
    cities.add(new City(8732, "	Hovedgård	"));
    cities.add(new City(8740, "	Brædstrup	"));
    cities.add(new City(8751, "	Gedved	"));
    cities.add(new City(8752, "	Østbirk	"));
    cities.add(new City(8762, "	Flemming	"));
    cities.add(new City(8763, "	Rask Mølle	"));
    cities.add(new City(8765, "	Klovborg	"));
    cities.add(new City(8766, "	Nørre Snede	"));
    cities.add(new City(8781, "	Stenderup	"));
    cities.add(new City(8783, "	Hornsyld	"));
    cities.add(new City(8800, "	Viborg	"));
    cities.add(new City(8830, "	Tjele	"));
    cities.add(new City(8831, "	Løgstrup	"));
    cities.add(new City(8832, "	Skals	"));
    cities.add(new City(8840, "	Rødkærsbro	"));
    cities.add(new City(8850, "	Bjerringbro	"));
    cities.add(new City(8860, "	Ulstrup	"));
    cities.add(new City(8870, "	Langå	"));
    cities.add(new City(8881, "	Thorsø	"));
    cities.add(new City(8882, "	Fårvang	"));
    cities.add(new City(8883, "	Gjern	"));
    cities.add(new City(8900, "	Randers C	"));
    cities.add(new City(8920, "	Randers NV	"));
    cities.add(new City(8930, "	Randers NØ	"));
    cities.add(new City(8940, "	Randers SV	"));
    cities.add(new City(8950, "	Ørsted	"));
    cities.add(new City(8960, "	Randers SØ	"));
    cities.add(new City(8961, "	Allingåbro	"));
    cities.add(new City(8963, "	Auning	"));
    cities.add(new City(8970, "	Havndal	"));
    cities.add(new City(8981, "	Spentrup	"));
    cities.add(new City(8983, "	Gjerlev J	"));
    cities.add(new City(8990, "	Fårup	"));
    cities.add(new City(9000, "	Aalborg	"));
    cities.add(new City(9200, "	Aalborg SV	"));
    cities.add(new City(9210, "	Aalborg SØ	"));
    cities.add(new City(9220, "	Aalborg Øst	"));
    cities.add(new City(9230, "	Svenstrup J	"));
    cities.add(new City(9240, "	Nibe	"));
    cities.add(new City(9260, "	Gistrup	"));
    cities.add(new City(9270, "	Klarup	"));
    cities.add(new City(9280, "	Storvorde	"));
    cities.add(new City(9293, "	Kongerslev	"));
    cities.add(new City(9300, "	Sæby	"));
    cities.add(new City(9310, "	Vodskov	"));
    cities.add(new City(9320, "	Hjallerup	"));
    cities.add(new City(9330, "	Dronninglund	"));
    cities.add(new City(9340, "	Asaa	"));
    cities.add(new City(9352, "	Dybvad	"));
    cities.add(new City(9362, "	Gandrup	"));
    cities.add(new City(9370, "	Hals	"));
    cities.add(new City(9380, "	Vestbjerg	"));
    cities.add(new City(9381, "	Sulsted	"));
    cities.add(new City(9382, "	Tylstrup	"));
    cities.add(new City(9400, "	Nørresundby	"));
    cities.add(new City(9430, "	Vadum	"));
    cities.add(new City(9440, "	Aabybro	"));
    cities.add(new City(9460, "	Brovst	"));
    cities.add(new City(9480, "	Løkken	"));
    cities.add(new City(9490, "	Pandrup	"));
    cities.add(new City(9492, "	Blokhus	"));
    cities.add(new City(9493, "	Saltum	"));
    cities.add(new City(9500, "	Hobro	"));
    cities.add(new City(9510, "	Arden	"));
    cities.add(new City(9520, "	Skørping	"));
    cities.add(new City(9530, "	Støvring	"));
    cities.add(new City(9541, "	Suldrup	"));
    cities.add(new City(9550, "	Mariager	"));
    cities.add(new City(9560, "	Hadsund	"));
    cities.add(new City(9574, "	Bælum	"));
    cities.add(new City(9575, "	Terndrup	"));
    cities.add(new City(9600, "	Aars	"));
    cities.add(new City(9610, "	Nørager	"));
    cities.add(new City(9620, "	Aalestrup	"));
    cities.add(new City(9631, "	Gedsted	"));
    cities.add(new City(9632, "	Møldrup	"));
    cities.add(new City(9640, "	Farsø	"));
    cities.add(new City(9670, "	Løgstør	"));
    cities.add(new City(9681, "	Ranum	"));
    cities.add(new City(9690, "	Fjerritslev	"));
    cities.add(new City(9700, "	Brønderslev	"));
    cities.add(new City(9740, "	Jerslev J	"));
    cities.add(new City(9750, "	Østervrå	"));
    cities.add(new City(9760, "	Vrå	"));
    cities.add(new City(9800, "	Hjørring	"));
    cities.add(new City(9830, "	Tårs	"));
    cities.add(new City(9850, "	Hirtshals	"));
    cities.add(new City(9870, "	Sindal	"));
    cities.add(new City(9881, "	Bindslev	"));
    cities.add(new City(9900, "	Frederikshavn	"));
    cities.add(new City(9940, "	Læsø	"));
    cities.add(new City(9970, "	Strandby	"));
    cities.add(new City(9981, "	Jerup	"));
    cities.add(new City(9982, "	Ålbæk	"));
    cities.add(new City(9990, "	Skagen	"));

  }
}
